version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwordfile:/mosquitto/config/passwordfile
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh", "mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
    env_file:
      - .env

volumes:
  mosquitto_data:
  mosquitto_log: